content:
  - name: posts
    label: Posts
    path: content/blog
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
