name: Publish

on:
  push:
    branches:
      - dev

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        env:
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: dist
          PUBLISH_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
